export const hardwareReportImportFixtures = {
  current: {
    format: "family-music-quest-hardware-report",
    version: 1,
    generatedAt: "2026-09-12T23:10:00.000Z",
    appVersion: "2.6.17",
    commit: "2489d750c78e917fe325d6033b682860c872f3c2",
    player: { id: "fixture-player", name: "Fixture Child" },
    platform: { platform: "Chrome OS", language: "en-CA", displayMode: "standalone" },
    fixtureFutureField: { preserved: true },
    guidedAcceptance: {
      format: "family-music-quest-guided-hardware-acceptance",
      version: 3,
      appVersion: "2.6.17",
      commit: null,
      sessionId: "FMQ-HW-2026-09-12-01",
      startedAt: "2026-09-12T22:45:00.000Z",
      completedAt: "2026-09-12T23:05:00.000Z",
      status: "complete",
      player: { id: "fixture-player", name: "Fixture Child" },
      platform: { platform: "Chrome OS", displayMode: "standalone" },
      audioDevice: { label: "Fixture microphone" },
      audioSettings: { sampleRate: 48000 },
      guitar: {
        status: "complete",
        quiet: { sampleCount: 36, noiseFloor: 0.004 },
        strings: [{ expected: { note: "E2" }, detectedNote: "E2", stable: true, retries: 0 }],
        repeated: { expected: { note: "A2" }, stable: true },
        silence: { scoreableReadings: 0 },
      },
      pianoMicrophone: {
        status: "complete",
        mode: "monophonic",
        notes: [{ expected: { note: "C4" }, detectedNote: "C4", stable: true, retries: 0 }],
        repeated: { expected: { note: "C4" }, stable: true },
      },
      midi: {
        status: "not-run",
        device: null,
        noteOn: null,
        noteOff: null,
        velocitySamples: [],
        polyphonyMax: 0,
        sustain: null,
        skipped: ["No physical MIDI keyboard available"],
      },
      humanObservations: {
        reaction: { answer: "yes", provenance: "child" },
        smooth: { answer: "yes", provenance: "child" },
      },
      humanEvidence: {
        adultResult: "not-decided",
        adultHelpRequired: "0",
        adultHelpNote: "Fixture only",
        childScoringTrust: "mostly",
        childComment: "Fixture child comment",
        testerNote: "Deterministic test fixture",
        evidenceReferences: ["fixture-video.mp4"],
      },
      warnings: ["Fixture warning"],
      testsNotPerformed: ["Guided Piano MIDI capability test", "Physical end-to-end latency measurement"],
      fixtureGuidedFutureField: { preserveMe: "yes" },
    },
  },
};
