import { hardwareReportImport } from "./hardwareReportImport";
import { hardwareReportImportFixtures } from "./hardwareReportImportFixtures";
const clone = <T,>(value:T):T => JSON.parse(JSON.stringify(value)) as T;
describe("hardwareReportImport", () => {
  it("imports the current v2.6.17 report shape and preserves source metadata and raw additive fields", () => { const result=hardwareReportImport.parseText(JSON.stringify(hardwareReportImportFixtures.current),"fmq-report.json"); expect(result.ok).toBe(true); if(!result.ok)return; expect(result.source.fmqSessionId).toBe("FMQ-HW-2026-09-12-01"); expect(result.source.reportVersion).toBe(1); expect(result.source.guidedVersion).toBe(3); expect(result.source.appVersion).toBe("2.6.17"); expect(result.source.commit).toBe("2489d750c78e917fe325d6033b682860c872f3c2"); expect(result.source.completedGuidedPaths).toEqual(["Guitar","Piano microphone"]); expect(result.source.testsNotPerformed).toEqual(hardwareReportImportFixtures.current.guidedAcceptance.testsNotPerformed); expect((result.source.rawReport.fixtureFutureField as {preserved:boolean}).preserved).toBe(true); expect(((result.source.rawReport.guidedAcceptance as Record<string,unknown>).fixtureGuidedFutureField as {preserveMe:string}).preserveMe).toBe("yes"); });
  it("keeps generated Guitar/Piano/MIDI and FMQ human evidence separate as source fields", () => { const result=hardwareReportImport.parseText(JSON.stringify(hardwareReportImportFixtures.current)); expect(result.ok).toBe(true); if(!result.ok)return; expect((result.source.guidedEvidence.guitar as {status:string}).status).toBe("complete"); expect((result.source.guidedEvidence.pianoMicrophone as {status:string}).status).toBe("complete"); expect((result.source.guidedEvidence.midi as {status:string}).status).toBe("not-run"); expect(result.source.humanEvidence).toEqual(hardwareReportImportFixtures.current.guidedAcceptance.humanEvidence); });
  it("rejects malformed and unrelated JSON", () => { expect(hardwareReportImport.parseText("{not json").ok).toBe(false); expect(hardwareReportImport.parseText(JSON.stringify({format:"something-else",version:1})).ok).toBe(false); });
  it("does not double-count the same session when only outer generatedAt changes", () => { const first=hardwareReportImport.parseText(JSON.stringify(hardwareReportImportFixtures.current)); const later=clone(hardwareReportImportFixtures.current); later.generatedAt="2026-09-12T23:20:00.000Z"; const second=hardwareReportImport.parseText(JSON.stringify(later)); expect(first.ok&&second.ok).toBe(true); if(!first.ok||!second.ok)return; expect(hardwareReportImport.compare([first.source],second.source).kind).toBe("duplicate"); expect(first.source.evidenceFingerprint).toBe(second.source.evidenceFingerprint); expect(first.source.rawFingerprint).not.toBe(second.source.rawFingerprint); });
  it("flags a meaningful same-session evidence change instead of silently overwriting", () => { const first=hardwareReportImport.parseText(JSON.stringify(hardwareReportImportFixtures.current)); const changed=clone(hardwareReportImportFixtures.current) as any; changed.generatedAt="2026-09-12T23:30:00.000Z"; changed.guidedAcceptance.midi.status="complete"; changed.guidedAcceptance.midi.noteOn={note:60}; const second=hardwareReportImport.parseText(JSON.stringify(changed)); expect(first.ok&&second.ok).toBe(true); if(!first.ok||!second.ok)return; expect(hardwareReportImport.compare([first.source],second.source).kind).toBe("conflict"); });
});
