import React from "react";
import { fireEvent, render, screen } from "@testing-library/react";
import App from "../App";
import { ThemeModeProvider } from "./themeMode";
import { sessionStore } from "./sessionStore";
import { hardwareReportImport } from "./hardwareReportImport";
import { hardwareReportImportFixtures } from "./hardwareReportImportFixtures";
const renderShell=()=>render(<ThemeModeProvider><App/></ThemeModeProvider>);
describe("FMQ Test Console session shell",()=>{
  beforeEach(()=>window.localStorage.removeItem(sessionStore.storageKey));
  it("keeps the acceptance disclaimer visible on Home",()=>{renderShell();expect(screen.getByText("Test Console records evidence only. Final FMQ acceptance decision: NOT DETERMINED BY THIS TOOL.")).toBeTruthy();});
  it("creates a durable revision-snapshotted session and resumes it after remount",()=>{const firstRender=renderShell();fireEvent.click(screen.getByRole("button",{name:/Create New Session/i}));expect(screen.getByText("Record the setup before touching the instrument.")).toBeTruthy();expect(screen.getByDisplayValue("v2.6.17")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/Create & Save Session/i}));expect(screen.getByText("Selected pack revisions")).toBeTruthy();expect(screen.getByText("Piano C3 / Lower-Range Acceptance")).toBeTruthy();expect(screen.getByText("issue-40-hardware-validation-2026-09-12-r1")).toBeTruthy();fireEvent.click(screen.getByRole("button",{name:/Save \/ Exit to Home/i}));expect(screen.getByTestId("resume-card")).toBeTruthy();firstRender.unmount();renderShell();expect(screen.getByTestId("resume-card")).toBeTruthy();expect(screen.getByRole("button",{name:/Resume/i})).toBeTruthy();});
  it("shows durable sessions in Prior Sessions without implying Issue PASS",()=>{renderShell();fireEvent.click(screen.getByRole("button",{name:/Create New Session/i}));fireEvent.click(screen.getByRole("button",{name:/Create & Save Session/i}));fireEvent.click(screen.getByRole("button",{name:/Save \/ Exit to Home/i}));fireEvent.click(screen.getByRole("button",{name:/Prior Sessions/i}));expect(screen.getByText("Prior local sessions")).toBeTruthy();expect(screen.getByText(/0\/9 steps recorded · Evidence incomplete/i)).toBeTruthy();expect(screen.getByText("Pack completion ≠ Issue PASS")).toBeTruthy();});
  it("autosaves runner disposition and cursor through a full remount",()=>{const firstRender=renderShell();fireEvent.click(screen.getByRole("button",{name:/Create New Session/i}));fireEvent.click(screen.getByRole("button",{name:/Create & Save Session/i}));fireEvent.click(screen.getByRole("button",{name:/Continue Guided Runner/i}));fireEvent.click(screen.getByRole("button",{name:"PASS"}));fireEvent.click(screen.getByRole("button",{name:/Next/i}));expect(screen.getByText(/Play C4 \(Middle C\) five separate times/i)).toBeTruthy();firstRender.unmount();renderShell();fireEvent.click(screen.getByRole("button",{name:/Resume/i}));fireEvent.click(screen.getByRole("button",{name:/Continue Guided Runner/i}));expect(screen.getByText(/Play C4 \(Middle C\) five separate times/i)).toBeTruthy();expect(screen.getAllByText("1 / 9 recorded").length).toBe(2);});
  it("shows persisted FMQ-generated evidence after a full app remount",()=>{const setup={fmqVersion:"v2.6.17",testDateTime:"2026-09-12T21:00",tester:"adult" as const,targetDevice:"Dell Chromebook 3100",browserMode:"installed-pwa" as const,guitarInput:"not-testing" as const,pianoInput:"internal-mic" as const,notes:""};let session=sessionStore.createSession(setup,["piano-c3-lower-range"]);const imported=hardwareReportImport.parseText(JSON.stringify(hardwareReportImportFixtures.current),"fixture.json");expect(imported.ok).toBe(true);if(!imported.ok)return;session=sessionStore.addImportedSource(session,imported.source);sessionStore.saveSession(session);const firstRender=renderShell();fireEvent.click(screen.getByRole("button",{name:/Resume/i}));expect(screen.getByText("FMQ-HW-2026-09-12-01")).toBeTruthy();expect(screen.getAllByText("FMQ-generated / guided evidence").length).toBeGreaterThan(0);firstRender.unmount();renderShell();fireEvent.click(screen.getByRole("button",{name:/Resume/i}));expect(screen.getByText("FMQ-HW-2026-09-12-01")).toBeTruthy();expect(screen.getByText(/Guided report/i)).toBeTruthy();});
});
