import { switchToDarkMode,switchToLightMode,switchToAutoMode,getCurrentThemeMode } from "./themeMode";
function createMediaQueryList(initialMatches:boolean,query="(prefers-color-scheme: dark)"){ let currentMatches=initialMatches; const mql:Partial<MediaQueryList>={ get matches(){return currentMatches;}, media:query,onchange:null,addListener:()=>{},removeListener:()=>{},addEventListener:()=>{},removeEventListener:()=>{},dispatchEvent:()=>false }; return Object.assign(mql,{setMatches(newMatches:boolean){currentMatches=newMatches;}}) as MediaQueryList & {setMatches:(matches:boolean)=>void}; }
describe("themeMode helper",()=>{ let originalMatchMedia:typeof window.matchMedia; beforeAll(()=>{originalMatchMedia=window.matchMedia;}); afterAll(()=>{window.matchMedia=originalMatchMedia;}); beforeEach(()=>{document.body.className=""; switchToLightMode();});
  it("should add the 'dark' class when switching to dark mode",()=>{switchToDarkMode(); expect(document.body.classList.contains("dark")).toBe(true);});
  it("should remove the 'dark' class when switching to light mode",()=>{document.body.classList.add("dark"); switchToLightMode(); expect(document.body.classList.contains("dark")).toBe(false);});
  it("should apply dark mode automatically when user prefers dark",()=>{window.matchMedia=(q:string)=>createMediaQueryList(true,q); switchToAutoMode(); expect(document.body.classList.contains("dark")).toBe(true);});
  it("should apply light mode automatically when user does not prefer dark",()=>{document.body.classList.add("dark"); window.matchMedia=(q:string)=>createMediaQueryList(false,q); switchToAutoMode(); expect(document.body.classList.contains("dark")).toBe(false);});
  it("should update theme when system preference changes in auto mode upon re-calling switchToAutoMode",()=>{window.matchMedia=(q:string)=>createMediaQueryList(false,q); switchToAutoMode(); expect(document.body.classList.contains("dark")).toBe(false); window.matchMedia=(q:string)=>createMediaQueryList(true,q); switchToAutoMode(); expect(document.body.classList.contains("dark")).toBe(true); window.matchMedia=(q:string)=>createMediaQueryList(false,q); switchToAutoMode(); expect(document.body.classList.contains("dark")).toBe(false);});
  it("should update theme when media query change event is triggered",()=>{const dummy=createMediaQueryList(false); window.matchMedia=()=>dummy; switchToAutoMode(); expect(document.body.classList.contains("dark")).toBe(false); dummy.setMatches(true); dummy.onchange?.({matches:true} as MediaQueryListEvent); expect(document.body.classList.contains("dark")).toBe(true); dummy.setMatches(false); dummy.onchange?.({matches:false} as MediaQueryListEvent); expect(document.body.classList.contains("dark")).toBe(false);});
  it("getCurrentThemeMode should return 'dark' when dark mode is set manually",()=>{switchToDarkMode(); expect(getCurrentThemeMode()).toBe("dark");});
  it("getCurrentThemeMode should return 'light' when light mode is set manually",()=>{switchToLightMode(); expect(getCurrentThemeMode()).toBe("light");});
  it("getCurrentThemeMode should return 'auto' when auto mode is enabled",()=>{window.matchMedia=(q:string)=>createMediaQueryList(true,q); switchToAutoMode(); expect(getCurrentThemeMode()).toBe("auto");});
});
