import { ArrowLeft, ArrowRight, CheckCircle2, CircleAlert, CircleSlash2, ClipboardCheck, Save, ShieldCheck } from "lucide-react";
import { Badge } from "./Badge";
import { Button } from "./Button";
import { Input } from "./Input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./Select";
import { Textarea } from "./Textarea";
import { sessionStore } from "../helpers/sessionStore";
import styles from "./GuidedRunner.module.css";
type ConsoleSession = ReturnType<typeof sessionStore.createSession>;
const resultLabel = (result: ReturnType<typeof sessionStore.getObservation>["result"]) => result === "pass" ? "PASS" : result === "problem" ? "PROBLEM" : result === "not-tested" ? "NOT TESTED" : "No disposition recorded";
export const GuidedRunner = ({ session, onSessionChange, onExit }: { session: ConsoleSession; onSessionChange: (session: ConsoleSession) => void; onExit: () => void; }) => {
  const cursor = sessionStore.getCursorItem(session); const current = cursor.item;
  if (!current) return <section className={styles.emptyRunner}><ClipboardCheck size={28} /><h2>No evidence steps in this session.</h2><Button onClick={onExit}>Return to session</Button></section>;
  const { pack, step } = current; const observation = sessionStore.getObservation(session, pack.id, step.id);
  const overallProgress = sessionStore.getProgress(session); const packProgress = sessionStore.getProgress(session, pack.id);
  const packStepIndex = pack.steps.findIndex((candidate) => candidate.id === step.id); const isFirst = cursor.index === 0; const isLast = cursor.index === cursor.total - 1;
  const updateObservation = (patch: Partial<typeof observation>) => onSessionChange(sessionStore.updateObservation(session, pack.id, step.id, patch));
  const move = (delta: -1 | 1) => onSessionChange(sessionStore.moveCursor(session, delta));
  return <div className={styles.runner} data-testid="guided-runner">
    <section className={styles.runnerHeader}><div><p className={styles.kicker}>Guided evidence runner</p><h2>{pack.title}</h2><div className={styles.issueRow}>{pack.issueRefs.map((issue) => <span key={issue}>{issue}</span>)}{pack.referenceOnly && <span>REFERENCE</span>}</div></div><Button variant="outline" onClick={onExit}><Save size={16} /> Save / Exit</Button></section>
    <section className={styles.progressPanel} aria-label="Evidence progress"><div><span>Session evidence</span><strong>{overallProgress.recorded} / {overallProgress.total} recorded</strong></div><div><span>This pack</span><strong>{packProgress.recorded} / {packProgress.total} recorded</strong></div><p>Recorded means a disposition was entered, including NOT TESTED. This is never a pass percentage.</p></section>
    <section className={styles.stepCard}><div className={styles.stepMeta}><span>Step {packStepIndex + 1} of {pack.steps.length}</span><code>{pack.revisionId}</code></div><p className={styles.kicker}>Do this now</p><h3>{step.instruction}</h3></section>
    <section className={styles.expectedCard}><ShieldCheck size={19} /><div><strong>Expected behavior</strong><p>{step.expected}</p><small>Expectation is reference text only. The tester chooses the result.</small></div></section>
    <section className={styles.resultPanel}><div className={styles.sectionTitleRow}><div><p className={styles.kicker}>Step disposition</p><h3>{resultLabel(observation.result)}</h3></div><Badge variant="outline">Manual choice</Badge></div><div className={styles.resultGrid}>
      <Button variant={observation.result === "pass" ? "secondary" : "outline"} className={observation.result === "pass" ? styles.resultSelected : ""} aria-pressed={observation.result === "pass"} onClick={() => updateObservation({ result: "pass" })}><CheckCircle2 size={18} /> PASS</Button>
      <Button variant={observation.result === "problem" ? "secondary" : "outline"} className={observation.result === "problem" ? styles.resultSelected : ""} aria-pressed={observation.result === "problem"} onClick={() => updateObservation({ result: "problem" })}><CircleAlert size={18} /> PROBLEM</Button>
      <Button variant={observation.result === "not-tested" ? "secondary" : "outline"} className={observation.result === "not-tested" ? styles.resultSelected : ""} aria-pressed={observation.result === "not-tested"} onClick={() => updateObservation({ result: "not-tested" })}><CircleSlash2 size={18} /> NOT TESTED</Button>
    </div></section>
    {pack.structuredEvidence?.kind === "piano40" && <section className={styles.structuredPanel} data-testid="piano40-evidence"><div className={styles.sectionTitleRow}><div><p className={styles.kicker}>Structured observation</p><h3>{pack.structuredEvidence.title}</h3></div><Badge variant="warning">#40</Badge></div><p className={styles.structuredNote}>{pack.structuredEvidence.note}</p><div className={styles.structuredGrid}>{pack.structuredEvidence.fields.map((field) => <label className={styles.field} key={field.key}><span>{field.label}</span><Input type={field.input === "count" ? "number" : "text"} min={field.input === "count" ? 0 : undefined} inputMode={field.input === "count" ? "numeric" : undefined} value={observation.structured[field.key] ?? ""} onChange={(event) => updateObservation({ structured: { [field.key]: event.target.value } })} /><small>{field.help}</small></label>)}</div></section>}
    <section className={styles.observationPanel}><p className={styles.kicker}>Manual evidence</p><div className={styles.fieldStack}><label className={styles.field}><span>Actual Behavior</span><Textarea rows={4} value={observation.actualBehavior} onChange={(event) => updateObservation({ actualBehavior: event.target.value })} placeholder="What actually happened on the Chromebook/instrument path?" /></label><label className={styles.field}><span>Notes</span><Textarea rows={3} value={observation.notes} onChange={(event) => updateObservation({ notes: event.target.value })} placeholder="Context, timing, child comments, setup details…" /></label><div className={styles.twoColumn}><div className={styles.field}><span>Reproduction frequency</span><Select value={observation.reproductionFrequency} onValueChange={(value) => updateObservation({ reproductionFrequency: value as typeof observation.reproductionFrequency })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="always">Always</SelectItem><SelectItem value="sometimes">Sometimes</SelectItem><SelectItem value="once">Once</SelectItem><SelectItem value="unknown">Unknown</SelectItem></SelectContent></Select></div><div className={styles.field}><span>Observation provenance</span><Select value={observation.provenance} onValueChange={(value) => updateObservation({ provenance: value as typeof observation.provenance })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="adult">Adult</SelectItem><SelectItem value="child">Child</SelectItem><SelectItem value="both">Both</SelectItem></SelectContent></Select></div></div><label className={styles.field}><span>Evidence filename / label <em>optional</em></span><Input value={observation.evidenceLabel} onChange={(event) => updateObservation({ evidenceLabel: event.target.value })} placeholder="IMG_2048.jpg, phone video 1, handwritten note…" /></label></div></section>
    <section className={styles.completionNotice}><strong>Pack completion rule</strong><p>{pack.completionRule}</p></section>
    <nav className={styles.navBar} aria-label="Guided step navigation"><Button variant="outline" size="lg" disabled={isFirst} onClick={() => move(-1)}><ArrowLeft size={18} /> Previous</Button><span>Autosaved locally</span><Button size="lg" disabled={isLast} onClick={() => move(1)}>Next <ArrowRight size={18} /></Button></nav>
  </div>;
};
